---
# tasks file for ansible-role-percona/

- name: RedHat | Download Percona Yum Repository Release
  yum: name="http://www.percona.com/downloads/percona-release/redhat/{{ percona_yum_release_version }}/percona-release-{{ percona_yum_release_version }}.noarch.rpm" state=present

- name: Install / Configure Percona Server
  include: install-percona-server.yml
